sudo: false

env:
  global:
    - GOPATH=~/gopath
    - PATH=${GOPATH}/bin:$PATH
    - NODE_VERSION="10.13.0"
    - RUBY_VERSION=2.1.1
    - GO111MODULE=on

matrix:
  allow_failures:
    - os: osx
  include:
  - os: linux
    addons:
      apt:
        packages:
          - rpm
          - gcc-mingw-w64
    language: go
    go: "1.11"
  - os: osx
    osx_image: xcode8.3
    language: go
    go: "1.11"

before_install:
- nvm install ${NODE_VERSION}
- nvm use ${NODE_VERSION}

script:
- |
  make install-deps || exit 1
  make dist || exit 1

  # On Linux, make a Windows release as well.
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    GOOS=windows CC=x86_64-w64-mingw32-gcc make dist || exit 1
  fi

  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    rvm install $RUBY_VERSION
    rvm use $RUBY_VERSION
    gem install fpm
    sudo apt-get -y install rpm
    make deb
    make rpm
  fi
